# https://docs.k3s.io/installation/private-registry
mirrors:
  # use same docker mirror as docker daemon
  docker.io:
    endpoint: ["${DOCKERD_REGISTRY_MIRROR}"]
    rewrite: {"^(.*)$": docker.io/$1}
  "*":
    endpoint: ["${DOCKERD_REGISTRY_MIRROR}"]
