name: Check PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: bump
        uses: zwaldowski/match-label-action@v1
        with:
          allowed: major,minor,patch

  comment:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        if: env.WORKFLOW_CONCLUSION == 'failure'
        uses: thollander/actions-comment-pull-request@1.0.2
        with:
          message: "Thanks for your contribution. Please apply one of the following labels to the PR: 'patch', 'minor', 'major'. See https://github.com/kokuwaio/k3s-maven-plugin#contributing for more information."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}