name: Lint

"on":
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request: {}

jobs:

  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: ibiqlik/action-yamllint@v3.1.0
        with:
          format: colored
          strict: true

  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: /github/workspace
