name: Release

on:
  push:
    branches: [ main ]
jobs:
  generate-version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.out.outputs.version }}

    steps:
      - uses: actions/checkout@v2

      - id: pr
        uses: actions-ecosystem/action-get-merged-pull-request@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - id: type
        shell: bash
        run: |
          
          if [[ "${{ steps.pr.outputs.labels }}" =~ "bug" ]]; then
            echo "Found"
          fi
          echo "not found"
