name: Snapshot

"on":
  workflow_dispatch: {}
  push: {}

jobs:

  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibiqlik/action-yamllint@v3
        with:
          format: colored
          strict: true

  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://avtodev/markdown-lint:v1
        with:
          args: /github/workspace

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - run: mvn -B dependency:go-offline
      - run: mvn -B verify
      - uses: dorny/test-reporter@v1
        if: failure()
        with:
          name: surefire
          path: '**/target/surefire-reports/*.xml'
          reporter: java-junit
          list-suites: failed
          list-tests: failed

  deploy:
    if: github.ref == 'refs/heads/main'
    needs:
      - yaml
      - markdown
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: maven
          server-id: sonatype-nexus
          server-username: SERVER_USERNAME
          server-password: SERVER_PASSWORD
      - run: mvn -B dependency:go-offline
      - run: mvn -B deploy -DskipTests
        env:
          SERVER_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
