name: Build

on:
  pull_request: {}
  push:
    branches: [main, "*.x"]

env:
  MAVEN_ARGS: --batch-mode --color=always --no-transfer-progress -P!deploy -P!site

jobs:

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://kokuwaio/markdownlint

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://kokuwaio/yamllint

  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: mvn $MAVEN_ARGS verify -Dmaven.test.skip -Dinvoker.skip

  surefire-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "matrix={"test":$(find src/test/java -name "*Test.java" -not -name "AbstractTest.java" -execdir basename {} ';' | sort | cut -d. -f1 | jq -R -s -c 'split("\n")[:-1]')}" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  surefire-test:
    runs-on: ubuntu-latest
    needs: surefire-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.surefire-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: mvn $MAVEN_ARGS -P!check test -Dtest=${{ matrix.test }} -Dmaven.test.redirectTestOutputToFile=false

  invoker-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "matrix={"test":$(ls -d src/it/*/ | cut -f3 -d'/' | sort | jq -R -s -c 'split("\n")[:-1]')}" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  invoker-test:
    runs-on: ubuntu-latest
    needs: invoker-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.invoker-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: mvn $MAVEN_ARGS -P!check verify -Dinvoker.test=${{ matrix.test }} -Dinvoker.streamLogs -Dmaven.test.skip
